/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ffsxsensbbanrgqx5xtq4oc65m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mf2gxv6275hpxomyovlnyx7fse",
    "aws_cognito_identity_pool_id": "us-east-1:724cd393-0a4f-43d7-b747-01b7b7a99534",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LgCkFvbuc",
    "aws_user_pools_web_client_id": "nvkj9ph45ekee1d4lhc4ajil1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
